package org.simple.annotation.demo ;

import org.simple.injector.adapter.InjectAdapter ;
import org.simple.injector.util.ViewFinder;


/* This class is generated by Simple ViewInjector, please don't modify! */ 
public class TestFragment$InjectAdapter implements InjectAdapter<TestFragment> { 

  public void injects(TestFragment target)  { 
      target.textView =  ViewFinder.findViewById(target, 2131099651  ) ; 
  }

 } 