package org.simple.annotation.demo ;

import org.simple.injector.adapter.ViewAdapter ;
import org.simple.injector.util.ViewFinder;


/* This class is generated by Simple ViewInjector, please don't modify! */ 
public class TestActivity$ViewAdapter implements ViewAdapter<TestActivity> { 

  public void findViews(TestActivity target)  { 
      target.mTextView =  ViewFinder.findViewById(target, 2131099648  ) ; 
      target.mTextView2 =  ViewFinder.findViewById(target, 2131099649  ) ; 
  }

 } 